/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as protectedIndexRouteImport } from './routes/(protected)/index'
import { Route as protectedResourcesRouteImport } from './routes/(protected)/resources'
import { Route as protectedProfileRouteImport } from './routes/(protected)/profile'
import { Route as protectedOrganisationsRouteImport } from './routes/(protected)/organisations'
import { Route as protectedNewsRouteImport } from './routes/(protected)/news'
import { Route as protectedSettingsRouteRouteImport } from './routes/(protected)/settings/route'
import { Route as protectedGroupsIndexRouteImport } from './routes/(protected)/groups/index'
import { Route as protectedUserUserIdRouteImport } from './routes/(protected)/user/$userId'
import { Route as protectedSettingsProfileEditRouteImport } from './routes/(protected)/settings/profile-edit'
import { Route as protectedSettingsProfileRouteImport } from './routes/(protected)/settings/profile'
import { Route as protectedSettingsPasswordResetRouteImport } from './routes/(protected)/settings/password-reset'
import { Route as protectedResourcePostResourceIdRouteImport } from './routes/(protected)/resource-post/$resourceId'
import { Route as protectedPostPostIdRouteImport } from './routes/(protected)/post/$postId'
import { Route as protectedNewsPostNewsIdRouteImport } from './routes/(protected)/news-post/$newsId'
import { Route as protectedGroupsCreateRouteImport } from './routes/(protected)/groups/create'
import { Route as protectedGroupsGroupIdRouteImport } from './routes/(protected)/groups/$groupId'
import { Route as protectedForumCategoryIdRouteImport } from './routes/(protected)/forum/$categoryId'
import { Route as protectedCreateCategoryGroupIdRouteImport } from './routes/(protected)/create-category/$groupId'
import { Route as protectedGroupsMyGroupIdRouteImport } from './routes/(protected)/groups/my/$groupId'
import { Route as protectedGroupsEditGroupIdRouteImport } from './routes/(protected)/groups/edit/$groupId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedResourcesRoute = protectedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedProfileRoute = protectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedOrganisationsRoute = protectedOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedNewsRoute = protectedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsRouteRoute = protectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedGroupsIndexRoute = protectedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUserUserIdRoute = protectedUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsProfileEditRoute =
  protectedSettingsProfileEditRouteImport.update({
    id: '/profile-edit',
    path: '/profile-edit',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsProfileRoute =
  protectedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsPasswordResetRoute =
  protectedSettingsPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedResourcePostResourceIdRoute =
  protectedResourcePostResourceIdRouteImport.update({
    id: '/resource-post/$resourceId',
    path: '/resource-post/$resourceId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedPostPostIdRoute = protectedPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedNewsPostNewsIdRoute = protectedNewsPostNewsIdRouteImport.update({
  id: '/news-post/$newsId',
  path: '/news-post/$newsId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedGroupsCreateRoute = protectedGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedGroupsGroupIdRoute = protectedGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedForumCategoryIdRoute =
  protectedForumCategoryIdRouteImport.update({
    id: '/forum/$categoryId',
    path: '/forum/$categoryId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedCreateCategoryGroupIdRoute =
  protectedCreateCategoryGroupIdRouteImport.update({
    id: '/create-category/$groupId',
    path: '/create-category/$groupId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedGroupsMyGroupIdRoute =
  protectedGroupsMyGroupIdRouteImport.update({
    id: '/groups/my/$groupId',
    path: '/groups/my/$groupId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedGroupsEditGroupIdRoute =
  protectedGroupsEditGroupIdRouteImport.update({
    id: '/groups/edit/$groupId',
    path: '/groups/edit/$groupId',
    getParentRoute: () => protectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/news': typeof protectedNewsRoute
  '/organisations': typeof protectedOrganisationsRoute
  '/profile': typeof protectedProfileRoute
  '/resources': typeof protectedResourcesRoute
  '/': typeof protectedIndexRoute
  '/create-category/$groupId': typeof protectedCreateCategoryGroupIdRoute
  '/forum/$categoryId': typeof protectedForumCategoryIdRoute
  '/groups/$groupId': typeof protectedGroupsGroupIdRoute
  '/groups/create': typeof protectedGroupsCreateRoute
  '/news-post/$newsId': typeof protectedNewsPostNewsIdRoute
  '/post/$postId': typeof protectedPostPostIdRoute
  '/resource-post/$resourceId': typeof protectedResourcePostResourceIdRoute
  '/settings/password-reset': typeof protectedSettingsPasswordResetRoute
  '/settings/profile': typeof protectedSettingsProfileRoute
  '/settings/profile-edit': typeof protectedSettingsProfileEditRoute
  '/user/$userId': typeof protectedUserUserIdRoute
  '/groups': typeof protectedGroupsIndexRoute
  '/groups/edit/$groupId': typeof protectedGroupsEditGroupIdRoute
  '/groups/my/$groupId': typeof protectedGroupsMyGroupIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/news': typeof protectedNewsRoute
  '/organisations': typeof protectedOrganisationsRoute
  '/profile': typeof protectedProfileRoute
  '/resources': typeof protectedResourcesRoute
  '/': typeof protectedIndexRoute
  '/create-category/$groupId': typeof protectedCreateCategoryGroupIdRoute
  '/forum/$categoryId': typeof protectedForumCategoryIdRoute
  '/groups/$groupId': typeof protectedGroupsGroupIdRoute
  '/groups/create': typeof protectedGroupsCreateRoute
  '/news-post/$newsId': typeof protectedNewsPostNewsIdRoute
  '/post/$postId': typeof protectedPostPostIdRoute
  '/resource-post/$resourceId': typeof protectedResourcePostResourceIdRoute
  '/settings/password-reset': typeof protectedSettingsPasswordResetRoute
  '/settings/profile': typeof protectedSettingsProfileRoute
  '/settings/profile-edit': typeof protectedSettingsProfileEditRoute
  '/user/$userId': typeof protectedUserUserIdRoute
  '/groups': typeof protectedGroupsIndexRoute
  '/groups/edit/$groupId': typeof protectedGroupsEditGroupIdRoute
  '/groups/my/$groupId': typeof protectedGroupsMyGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/(protected)/settings': typeof protectedSettingsRouteRouteWithChildren
  '/(protected)/news': typeof protectedNewsRoute
  '/(protected)/organisations': typeof protectedOrganisationsRoute
  '/(protected)/profile': typeof protectedProfileRoute
  '/(protected)/resources': typeof protectedResourcesRoute
  '/(protected)/': typeof protectedIndexRoute
  '/(protected)/create-category/$groupId': typeof protectedCreateCategoryGroupIdRoute
  '/(protected)/forum/$categoryId': typeof protectedForumCategoryIdRoute
  '/(protected)/groups/$groupId': typeof protectedGroupsGroupIdRoute
  '/(protected)/groups/create': typeof protectedGroupsCreateRoute
  '/(protected)/news-post/$newsId': typeof protectedNewsPostNewsIdRoute
  '/(protected)/post/$postId': typeof protectedPostPostIdRoute
  '/(protected)/resource-post/$resourceId': typeof protectedResourcePostResourceIdRoute
  '/(protected)/settings/password-reset': typeof protectedSettingsPasswordResetRoute
  '/(protected)/settings/profile': typeof protectedSettingsProfileRoute
  '/(protected)/settings/profile-edit': typeof protectedSettingsProfileEditRoute
  '/(protected)/user/$userId': typeof protectedUserUserIdRoute
  '/(protected)/groups/': typeof protectedGroupsIndexRoute
  '/(protected)/groups/edit/$groupId': typeof protectedGroupsEditGroupIdRoute
  '/(protected)/groups/my/$groupId': typeof protectedGroupsMyGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/registration'
    | '/verify-email'
    | '/settings'
    | '/news'
    | '/organisations'
    | '/profile'
    | '/resources'
    | '/'
    | '/create-category/$groupId'
    | '/forum/$categoryId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/news-post/$newsId'
    | '/post/$postId'
    | '/resource-post/$resourceId'
    | '/settings/password-reset'
    | '/settings/profile'
    | '/settings/profile-edit'
    | '/user/$userId'
    | '/groups'
    | '/groups/edit/$groupId'
    | '/groups/my/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/registration'
    | '/verify-email'
    | '/settings'
    | '/news'
    | '/organisations'
    | '/profile'
    | '/resources'
    | '/'
    | '/create-category/$groupId'
    | '/forum/$categoryId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/news-post/$newsId'
    | '/post/$postId'
    | '/resource-post/$resourceId'
    | '/settings/password-reset'
    | '/settings/profile'
    | '/settings/profile-edit'
    | '/user/$userId'
    | '/groups'
    | '/groups/edit/$groupId'
    | '/groups/my/$groupId'
  id:
    | '__root__'
    | '/(protected)'
    | '/about'
    | '/login'
    | '/registration'
    | '/verify-email'
    | '/(protected)/settings'
    | '/(protected)/news'
    | '/(protected)/organisations'
    | '/(protected)/profile'
    | '/(protected)/resources'
    | '/(protected)/'
    | '/(protected)/create-category/$groupId'
    | '/(protected)/forum/$categoryId'
    | '/(protected)/groups/$groupId'
    | '/(protected)/groups/create'
    | '/(protected)/news-post/$newsId'
    | '/(protected)/post/$postId'
    | '/(protected)/resource-post/$resourceId'
    | '/(protected)/settings/password-reset'
    | '/(protected)/settings/profile'
    | '/(protected)/settings/profile-edit'
    | '/(protected)/user/$userId'
    | '/(protected)/groups/'
    | '/(protected)/groups/edit/$groupId'
    | '/(protected)/groups/my/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegistrationRoute: typeof RegistrationRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/resources': {
      id: '/(protected)/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof protectedResourcesRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/profile': {
      id: '/(protected)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedProfileRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/organisations': {
      id: '/(protected)/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof protectedOrganisationsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/news': {
      id: '/(protected)/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof protectedNewsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/': {
      id: '/(protected)/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof protectedGroupsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/user/$userId': {
      id: '/(protected)/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof protectedUserUserIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings/profile-edit': {
      id: '/(protected)/settings/profile-edit'
      path: '/profile-edit'
      fullPath: '/settings/profile-edit'
      preLoaderRoute: typeof protectedSettingsProfileEditRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/profile': {
      id: '/(protected)/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof protectedSettingsProfileRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/password-reset': {
      id: '/(protected)/settings/password-reset'
      path: '/password-reset'
      fullPath: '/settings/password-reset'
      preLoaderRoute: typeof protectedSettingsPasswordResetRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/resource-post/$resourceId': {
      id: '/(protected)/resource-post/$resourceId'
      path: '/resource-post/$resourceId'
      fullPath: '/resource-post/$resourceId'
      preLoaderRoute: typeof protectedResourcePostResourceIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/post/$postId': {
      id: '/(protected)/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof protectedPostPostIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/news-post/$newsId': {
      id: '/(protected)/news-post/$newsId'
      path: '/news-post/$newsId'
      fullPath: '/news-post/$newsId'
      preLoaderRoute: typeof protectedNewsPostNewsIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/create': {
      id: '/(protected)/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof protectedGroupsCreateRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/$groupId': {
      id: '/(protected)/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof protectedGroupsGroupIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/forum/$categoryId': {
      id: '/(protected)/forum/$categoryId'
      path: '/forum/$categoryId'
      fullPath: '/forum/$categoryId'
      preLoaderRoute: typeof protectedForumCategoryIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/create-category/$groupId': {
      id: '/(protected)/create-category/$groupId'
      path: '/create-category/$groupId'
      fullPath: '/create-category/$groupId'
      preLoaderRoute: typeof protectedCreateCategoryGroupIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/my/$groupId': {
      id: '/(protected)/groups/my/$groupId'
      path: '/groups/my/$groupId'
      fullPath: '/groups/my/$groupId'
      preLoaderRoute: typeof protectedGroupsMyGroupIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/edit/$groupId': {
      id: '/(protected)/groups/edit/$groupId'
      path: '/groups/edit/$groupId'
      fullPath: '/groups/edit/$groupId'
      preLoaderRoute: typeof protectedGroupsEditGroupIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedSettingsRouteRouteChildren {
  protectedSettingsPasswordResetRoute: typeof protectedSettingsPasswordResetRoute
  protectedSettingsProfileRoute: typeof protectedSettingsProfileRoute
  protectedSettingsProfileEditRoute: typeof protectedSettingsProfileEditRoute
}

const protectedSettingsRouteRouteChildren: protectedSettingsRouteRouteChildren =
  {
    protectedSettingsPasswordResetRoute: protectedSettingsPasswordResetRoute,
    protectedSettingsProfileRoute: protectedSettingsProfileRoute,
    protectedSettingsProfileEditRoute: protectedSettingsProfileEditRoute,
  }

const protectedSettingsRouteRouteWithChildren =
  protectedSettingsRouteRoute._addFileChildren(
    protectedSettingsRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedSettingsRouteRoute: typeof protectedSettingsRouteRouteWithChildren
  protectedNewsRoute: typeof protectedNewsRoute
  protectedOrganisationsRoute: typeof protectedOrganisationsRoute
  protectedProfileRoute: typeof protectedProfileRoute
  protectedResourcesRoute: typeof protectedResourcesRoute
  protectedIndexRoute: typeof protectedIndexRoute
  protectedCreateCategoryGroupIdRoute: typeof protectedCreateCategoryGroupIdRoute
  protectedForumCategoryIdRoute: typeof protectedForumCategoryIdRoute
  protectedGroupsGroupIdRoute: typeof protectedGroupsGroupIdRoute
  protectedGroupsCreateRoute: typeof protectedGroupsCreateRoute
  protectedNewsPostNewsIdRoute: typeof protectedNewsPostNewsIdRoute
  protectedPostPostIdRoute: typeof protectedPostPostIdRoute
  protectedResourcePostResourceIdRoute: typeof protectedResourcePostResourceIdRoute
  protectedUserUserIdRoute: typeof protectedUserUserIdRoute
  protectedGroupsIndexRoute: typeof protectedGroupsIndexRoute
  protectedGroupsEditGroupIdRoute: typeof protectedGroupsEditGroupIdRoute
  protectedGroupsMyGroupIdRoute: typeof protectedGroupsMyGroupIdRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedSettingsRouteRoute: protectedSettingsRouteRouteWithChildren,
  protectedNewsRoute: protectedNewsRoute,
  protectedOrganisationsRoute: protectedOrganisationsRoute,
  protectedProfileRoute: protectedProfileRoute,
  protectedResourcesRoute: protectedResourcesRoute,
  protectedIndexRoute: protectedIndexRoute,
  protectedCreateCategoryGroupIdRoute: protectedCreateCategoryGroupIdRoute,
  protectedForumCategoryIdRoute: protectedForumCategoryIdRoute,
  protectedGroupsGroupIdRoute: protectedGroupsGroupIdRoute,
  protectedGroupsCreateRoute: protectedGroupsCreateRoute,
  protectedNewsPostNewsIdRoute: protectedNewsPostNewsIdRoute,
  protectedPostPostIdRoute: protectedPostPostIdRoute,
  protectedResourcePostResourceIdRoute: protectedResourcePostResourceIdRoute,
  protectedUserUserIdRoute: protectedUserUserIdRoute,
  protectedGroupsIndexRoute: protectedGroupsIndexRoute,
  protectedGroupsEditGroupIdRoute: protectedGroupsEditGroupIdRoute,
  protectedGroupsMyGroupIdRoute: protectedGroupsMyGroupIdRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegistrationRoute: RegistrationRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
