/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as protectedIndexRouteImport } from './routes/(protected)/index'
import { Route as protectedProfileRouteImport } from './routes/(protected)/profile'
import { Route as protectedOrganisationsRouteImport } from './routes/(protected)/organisations'
import { Route as protectedSettingsRouteRouteImport } from './routes/(protected)/settings/route'
import { Route as protectedResourcesIndexRouteImport } from './routes/(protected)/resources/index'
import { Route as protectedOrganizationsIndexRouteImport } from './routes/(protected)/organizations/index'
import { Route as protectedNewsIndexRouteImport } from './routes/(protected)/news/index'
import { Route as protectedGroupsIndexRouteImport } from './routes/(protected)/groups/index'
import { Route as protectedUserUserIdRouteImport } from './routes/(protected)/user/$userId'
import { Route as protectedSettingsProfileEditRouteImport } from './routes/(protected)/settings/profile-edit'
import { Route as protectedSettingsProfileRouteImport } from './routes/(protected)/settings/profile'
import { Route as protectedSettingsPasswordResetRouteImport } from './routes/(protected)/settings/password-reset'
import { Route as protectedResourcesResourceIdRouteImport } from './routes/(protected)/resources/$resourceId'
import { Route as protectedPostPostIdRouteImport } from './routes/(protected)/post/$postId'
import { Route as protectedOrganizationsOrganizationIdRouteImport } from './routes/(protected)/organizations/$organizationId'
import { Route as protectedNewsNewsIdRouteImport } from './routes/(protected)/news/$newsId'
import { Route as protectedGroupsCreateRouteImport } from './routes/(protected)/groups/create'
import { Route as protectedGroupsGroupIdRouteImport } from './routes/(protected)/groups/$groupId'
import { Route as protectedForumCategoryIdRouteImport } from './routes/(protected)/forum/$categoryId'
import { Route as protectedCreateCategoryGroupIdRouteImport } from './routes/(protected)/create-category/$groupId'
import { Route as protectedGroupsMyGroupIdRouteImport } from './routes/(protected)/groups/my/$groupId'
import { Route as protectedGroupsEditGroupIdRouteImport } from './routes/(protected)/groups/edit/$groupId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedProfileRoute = protectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedOrganisationsRoute = protectedOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsRouteRoute = protectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedResourcesIndexRoute = protectedResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedOrganizationsIndexRoute =
  protectedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedNewsIndexRoute = protectedNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedGroupsIndexRoute = protectedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUserUserIdRoute = protectedUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsProfileEditRoute =
  protectedSettingsProfileEditRouteImport.update({
    id: '/profile-edit',
    path: '/profile-edit',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsProfileRoute =
  protectedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsPasswordResetRoute =
  protectedSettingsPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedResourcesResourceIdRoute =
  protectedResourcesResourceIdRouteImport.update({
    id: '/resources/$resourceId',
    path: '/resources/$resourceId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedPostPostIdRoute = protectedPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedOrganizationsOrganizationIdRoute =
  protectedOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedNewsNewsIdRoute = protectedNewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedGroupsCreateRoute = protectedGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedGroupsGroupIdRoute = protectedGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedForumCategoryIdRoute =
  protectedForumCategoryIdRouteImport.update({
    id: '/forum/$categoryId',
    path: '/forum/$categoryId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedCreateCategoryGroupIdRoute =
  protectedCreateCategoryGroupIdRouteImport.update({
    id: '/create-category/$groupId',
    path: '/create-category/$groupId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedGroupsMyGroupIdRoute =
  protectedGroupsMyGroupIdRouteImport.update({
    id: '/groups/my/$groupId',
    path: '/groups/my/$groupId',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedGroupsEditGroupIdRoute =
  protectedGroupsEditGroupIdRouteImport.update({
    id: '/groups/edit/$groupId',
    path: '/groups/edit/$groupId',
    getParentRoute: () => protectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registration': typeof RegistrationRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/organisations': typeof protectedOrganisationsRoute
  '/profile': typeof protectedProfileRoute
  '/': typeof protectedIndexRoute
  '/create-category/$groupId': typeof protectedCreateCategoryGroupIdRoute
  '/forum/$categoryId': typeof protectedForumCategoryIdRoute
  '/groups/$groupId': typeof protectedGroupsGroupIdRoute
  '/groups/create': typeof protectedGroupsCreateRoute
  '/news/$newsId': typeof protectedNewsNewsIdRoute
  '/organizations/$organizationId': typeof protectedOrganizationsOrganizationIdRoute
  '/post/$postId': typeof protectedPostPostIdRoute
  '/resources/$resourceId': typeof protectedResourcesResourceIdRoute
  '/settings/password-reset': typeof protectedSettingsPasswordResetRoute
  '/settings/profile': typeof protectedSettingsProfileRoute
  '/settings/profile-edit': typeof protectedSettingsProfileEditRoute
  '/user/$userId': typeof protectedUserUserIdRoute
  '/groups': typeof protectedGroupsIndexRoute
  '/news': typeof protectedNewsIndexRoute
  '/organizations': typeof protectedOrganizationsIndexRoute
  '/resources': typeof protectedResourcesIndexRoute
  '/groups/edit/$groupId': typeof protectedGroupsEditGroupIdRoute
  '/groups/my/$groupId': typeof protectedGroupsMyGroupIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registration': typeof RegistrationRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/organisations': typeof protectedOrganisationsRoute
  '/profile': typeof protectedProfileRoute
  '/': typeof protectedIndexRoute
  '/create-category/$groupId': typeof protectedCreateCategoryGroupIdRoute
  '/forum/$categoryId': typeof protectedForumCategoryIdRoute
  '/groups/$groupId': typeof protectedGroupsGroupIdRoute
  '/groups/create': typeof protectedGroupsCreateRoute
  '/news/$newsId': typeof protectedNewsNewsIdRoute
  '/organizations/$organizationId': typeof protectedOrganizationsOrganizationIdRoute
  '/post/$postId': typeof protectedPostPostIdRoute
  '/resources/$resourceId': typeof protectedResourcesResourceIdRoute
  '/settings/password-reset': typeof protectedSettingsPasswordResetRoute
  '/settings/profile': typeof protectedSettingsProfileRoute
  '/settings/profile-edit': typeof protectedSettingsProfileEditRoute
  '/user/$userId': typeof protectedUserUserIdRoute
  '/groups': typeof protectedGroupsIndexRoute
  '/news': typeof protectedNewsIndexRoute
  '/organizations': typeof protectedOrganizationsIndexRoute
  '/resources': typeof protectedResourcesIndexRoute
  '/groups/edit/$groupId': typeof protectedGroupsEditGroupIdRoute
  '/groups/my/$groupId': typeof protectedGroupsMyGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/registration': typeof RegistrationRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/verify-email': typeof VerifyEmailRoute
  '/(protected)/settings': typeof protectedSettingsRouteRouteWithChildren
  '/(protected)/organisations': typeof protectedOrganisationsRoute
  '/(protected)/profile': typeof protectedProfileRoute
  '/(protected)/': typeof protectedIndexRoute
  '/(protected)/create-category/$groupId': typeof protectedCreateCategoryGroupIdRoute
  '/(protected)/forum/$categoryId': typeof protectedForumCategoryIdRoute
  '/(protected)/groups/$groupId': typeof protectedGroupsGroupIdRoute
  '/(protected)/groups/create': typeof protectedGroupsCreateRoute
  '/(protected)/news/$newsId': typeof protectedNewsNewsIdRoute
  '/(protected)/organizations/$organizationId': typeof protectedOrganizationsOrganizationIdRoute
  '/(protected)/post/$postId': typeof protectedPostPostIdRoute
  '/(protected)/resources/$resourceId': typeof protectedResourcesResourceIdRoute
  '/(protected)/settings/password-reset': typeof protectedSettingsPasswordResetRoute
  '/(protected)/settings/profile': typeof protectedSettingsProfileRoute
  '/(protected)/settings/profile-edit': typeof protectedSettingsProfileEditRoute
  '/(protected)/user/$userId': typeof protectedUserUserIdRoute
  '/(protected)/groups/': typeof protectedGroupsIndexRoute
  '/(protected)/news/': typeof protectedNewsIndexRoute
  '/(protected)/organizations/': typeof protectedOrganizationsIndexRoute
  '/(protected)/resources/': typeof protectedResourcesIndexRoute
  '/(protected)/groups/edit/$groupId': typeof protectedGroupsEditGroupIdRoute
  '/(protected)/groups/my/$groupId': typeof protectedGroupsMyGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/privacy-policy'
    | '/registration'
    | '/terms-of-service'
    | '/verify-email'
    | '/settings'
    | '/organisations'
    | '/profile'
    | '/'
    | '/create-category/$groupId'
    | '/forum/$categoryId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/news/$newsId'
    | '/organizations/$organizationId'
    | '/post/$postId'
    | '/resources/$resourceId'
    | '/settings/password-reset'
    | '/settings/profile'
    | '/settings/profile-edit'
    | '/user/$userId'
    | '/groups'
    | '/news'
    | '/organizations'
    | '/resources'
    | '/groups/edit/$groupId'
    | '/groups/my/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/privacy-policy'
    | '/registration'
    | '/terms-of-service'
    | '/verify-email'
    | '/settings'
    | '/organisations'
    | '/profile'
    | '/'
    | '/create-category/$groupId'
    | '/forum/$categoryId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/news/$newsId'
    | '/organizations/$organizationId'
    | '/post/$postId'
    | '/resources/$resourceId'
    | '/settings/password-reset'
    | '/settings/profile'
    | '/settings/profile-edit'
    | '/user/$userId'
    | '/groups'
    | '/news'
    | '/organizations'
    | '/resources'
    | '/groups/edit/$groupId'
    | '/groups/my/$groupId'
  id:
    | '__root__'
    | '/(protected)'
    | '/about'
    | '/login'
    | '/privacy-policy'
    | '/registration'
    | '/terms-of-service'
    | '/verify-email'
    | '/(protected)/settings'
    | '/(protected)/organisations'
    | '/(protected)/profile'
    | '/(protected)/'
    | '/(protected)/create-category/$groupId'
    | '/(protected)/forum/$categoryId'
    | '/(protected)/groups/$groupId'
    | '/(protected)/groups/create'
    | '/(protected)/news/$newsId'
    | '/(protected)/organizations/$organizationId'
    | '/(protected)/post/$postId'
    | '/(protected)/resources/$resourceId'
    | '/(protected)/settings/password-reset'
    | '/(protected)/settings/profile'
    | '/(protected)/settings/profile-edit'
    | '/(protected)/user/$userId'
    | '/(protected)/groups/'
    | '/(protected)/news/'
    | '/(protected)/organizations/'
    | '/(protected)/resources/'
    | '/(protected)/groups/edit/$groupId'
    | '/(protected)/groups/my/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegistrationRoute: typeof RegistrationRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/profile': {
      id: '/(protected)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedProfileRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/organisations': {
      id: '/(protected)/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof protectedOrganisationsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/resources/': {
      id: '/(protected)/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof protectedResourcesIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/organizations/': {
      id: '/(protected)/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof protectedOrganizationsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/news/': {
      id: '/(protected)/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof protectedNewsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/': {
      id: '/(protected)/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof protectedGroupsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/user/$userId': {
      id: '/(protected)/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof protectedUserUserIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings/profile-edit': {
      id: '/(protected)/settings/profile-edit'
      path: '/profile-edit'
      fullPath: '/settings/profile-edit'
      preLoaderRoute: typeof protectedSettingsProfileEditRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/profile': {
      id: '/(protected)/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof protectedSettingsProfileRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/password-reset': {
      id: '/(protected)/settings/password-reset'
      path: '/password-reset'
      fullPath: '/settings/password-reset'
      preLoaderRoute: typeof protectedSettingsPasswordResetRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/resources/$resourceId': {
      id: '/(protected)/resources/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof protectedResourcesResourceIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/post/$postId': {
      id: '/(protected)/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof protectedPostPostIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/organizations/$organizationId': {
      id: '/(protected)/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof protectedOrganizationsOrganizationIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/news/$newsId': {
      id: '/(protected)/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof protectedNewsNewsIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/create': {
      id: '/(protected)/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof protectedGroupsCreateRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/$groupId': {
      id: '/(protected)/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof protectedGroupsGroupIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/forum/$categoryId': {
      id: '/(protected)/forum/$categoryId'
      path: '/forum/$categoryId'
      fullPath: '/forum/$categoryId'
      preLoaderRoute: typeof protectedForumCategoryIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/create-category/$groupId': {
      id: '/(protected)/create-category/$groupId'
      path: '/create-category/$groupId'
      fullPath: '/create-category/$groupId'
      preLoaderRoute: typeof protectedCreateCategoryGroupIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/my/$groupId': {
      id: '/(protected)/groups/my/$groupId'
      path: '/groups/my/$groupId'
      fullPath: '/groups/my/$groupId'
      preLoaderRoute: typeof protectedGroupsMyGroupIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/groups/edit/$groupId': {
      id: '/(protected)/groups/edit/$groupId'
      path: '/groups/edit/$groupId'
      fullPath: '/groups/edit/$groupId'
      preLoaderRoute: typeof protectedGroupsEditGroupIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedSettingsRouteRouteChildren {
  protectedSettingsPasswordResetRoute: typeof protectedSettingsPasswordResetRoute
  protectedSettingsProfileRoute: typeof protectedSettingsProfileRoute
  protectedSettingsProfileEditRoute: typeof protectedSettingsProfileEditRoute
}

const protectedSettingsRouteRouteChildren: protectedSettingsRouteRouteChildren =
  {
    protectedSettingsPasswordResetRoute: protectedSettingsPasswordResetRoute,
    protectedSettingsProfileRoute: protectedSettingsProfileRoute,
    protectedSettingsProfileEditRoute: protectedSettingsProfileEditRoute,
  }

const protectedSettingsRouteRouteWithChildren =
  protectedSettingsRouteRoute._addFileChildren(
    protectedSettingsRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedSettingsRouteRoute: typeof protectedSettingsRouteRouteWithChildren
  protectedOrganisationsRoute: typeof protectedOrganisationsRoute
  protectedProfileRoute: typeof protectedProfileRoute
  protectedIndexRoute: typeof protectedIndexRoute
  protectedCreateCategoryGroupIdRoute: typeof protectedCreateCategoryGroupIdRoute
  protectedForumCategoryIdRoute: typeof protectedForumCategoryIdRoute
  protectedGroupsGroupIdRoute: typeof protectedGroupsGroupIdRoute
  protectedGroupsCreateRoute: typeof protectedGroupsCreateRoute
  protectedNewsNewsIdRoute: typeof protectedNewsNewsIdRoute
  protectedOrganizationsOrganizationIdRoute: typeof protectedOrganizationsOrganizationIdRoute
  protectedPostPostIdRoute: typeof protectedPostPostIdRoute
  protectedResourcesResourceIdRoute: typeof protectedResourcesResourceIdRoute
  protectedUserUserIdRoute: typeof protectedUserUserIdRoute
  protectedGroupsIndexRoute: typeof protectedGroupsIndexRoute
  protectedNewsIndexRoute: typeof protectedNewsIndexRoute
  protectedOrganizationsIndexRoute: typeof protectedOrganizationsIndexRoute
  protectedResourcesIndexRoute: typeof protectedResourcesIndexRoute
  protectedGroupsEditGroupIdRoute: typeof protectedGroupsEditGroupIdRoute
  protectedGroupsMyGroupIdRoute: typeof protectedGroupsMyGroupIdRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedSettingsRouteRoute: protectedSettingsRouteRouteWithChildren,
  protectedOrganisationsRoute: protectedOrganisationsRoute,
  protectedProfileRoute: protectedProfileRoute,
  protectedIndexRoute: protectedIndexRoute,
  protectedCreateCategoryGroupIdRoute: protectedCreateCategoryGroupIdRoute,
  protectedForumCategoryIdRoute: protectedForumCategoryIdRoute,
  protectedGroupsGroupIdRoute: protectedGroupsGroupIdRoute,
  protectedGroupsCreateRoute: protectedGroupsCreateRoute,
  protectedNewsNewsIdRoute: protectedNewsNewsIdRoute,
  protectedOrganizationsOrganizationIdRoute:
    protectedOrganizationsOrganizationIdRoute,
  protectedPostPostIdRoute: protectedPostPostIdRoute,
  protectedResourcesResourceIdRoute: protectedResourcesResourceIdRoute,
  protectedUserUserIdRoute: protectedUserUserIdRoute,
  protectedGroupsIndexRoute: protectedGroupsIndexRoute,
  protectedNewsIndexRoute: protectedNewsIndexRoute,
  protectedOrganizationsIndexRoute: protectedOrganizationsIndexRoute,
  protectedResourcesIndexRoute: protectedResourcesIndexRoute,
  protectedGroupsEditGroupIdRoute: protectedGroupsEditGroupIdRoute,
  protectedGroupsMyGroupIdRoute: protectedGroupsMyGroupIdRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegistrationRoute: RegistrationRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
