/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as protectedIndexRouteImport } from './routes/(protected)/index'
import { Route as protectedResourcesRouteImport } from './routes/(protected)/resources'
import { Route as protectedProfileRouteImport } from './routes/(protected)/profile'
import { Route as protectedNewsRouteImport } from './routes/(protected)/news'
import { Route as protectedSettingsRouteRouteImport } from './routes/(protected)/settings/route'
import { Route as protectedUserUserIdRouteImport } from './routes/(protected)/user/$userId'
import { Route as protectedSettingsProfileEditRouteImport } from './routes/(protected)/settings/profile-edit'
import { Route as protectedSettingsProfileRouteImport } from './routes/(protected)/settings/profile'
import { Route as protectedSettingsPasswordResetRouteImport } from './routes/(protected)/settings/password-reset'
import { Route as protectedSettingsOrganisationsRouteImport } from './routes/(protected)/settings/organisations'
import { Route as protectedSettingsGroupsRouteImport } from './routes/(protected)/settings/groups'
import { Route as protectedPostPostIdRouteImport } from './routes/(protected)/post/$postId'
import { Route as protectedForumCategoryIdRouteImport } from './routes/(protected)/forum/$categoryId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedResourcesRoute = protectedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedProfileRoute = protectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedNewsRoute = protectedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsRouteRoute = protectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUserUserIdRoute = protectedUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsProfileEditRoute =
  protectedSettingsProfileEditRouteImport.update({
    id: '/profile-edit',
    path: '/profile-edit',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsProfileRoute =
  protectedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsPasswordResetRoute =
  protectedSettingsPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsOrganisationsRoute =
  protectedSettingsOrganisationsRouteImport.update({
    id: '/organisations',
    path: '/organisations',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsGroupsRoute = protectedSettingsGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => protectedSettingsRouteRoute,
} as any)
const protectedPostPostIdRoute = protectedPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedForumCategoryIdRoute =
  protectedForumCategoryIdRouteImport.update({
    id: '/forum/$categoryId',
    path: '/forum/$categoryId',
    getParentRoute: () => protectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/news': typeof protectedNewsRoute
  '/profile': typeof protectedProfileRoute
  '/resources': typeof protectedResourcesRoute
  '/': typeof protectedIndexRoute
  '/forum/$categoryId': typeof protectedForumCategoryIdRoute
  '/post/$postId': typeof protectedPostPostIdRoute
  '/settings/groups': typeof protectedSettingsGroupsRoute
  '/settings/organisations': typeof protectedSettingsOrganisationsRoute
  '/settings/password-reset': typeof protectedSettingsPasswordResetRoute
  '/settings/profile': typeof protectedSettingsProfileRoute
  '/settings/profile-edit': typeof protectedSettingsProfileEditRoute
  '/user/$userId': typeof protectedUserUserIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/news': typeof protectedNewsRoute
  '/profile': typeof protectedProfileRoute
  '/resources': typeof protectedResourcesRoute
  '/': typeof protectedIndexRoute
  '/forum/$categoryId': typeof protectedForumCategoryIdRoute
  '/post/$postId': typeof protectedPostPostIdRoute
  '/settings/groups': typeof protectedSettingsGroupsRoute
  '/settings/organisations': typeof protectedSettingsOrganisationsRoute
  '/settings/password-reset': typeof protectedSettingsPasswordResetRoute
  '/settings/profile': typeof protectedSettingsProfileRoute
  '/settings/profile-edit': typeof protectedSettingsProfileEditRoute
  '/user/$userId': typeof protectedUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/(protected)/settings': typeof protectedSettingsRouteRouteWithChildren
  '/(protected)/news': typeof protectedNewsRoute
  '/(protected)/profile': typeof protectedProfileRoute
  '/(protected)/resources': typeof protectedResourcesRoute
  '/(protected)/': typeof protectedIndexRoute
  '/(protected)/forum/$categoryId': typeof protectedForumCategoryIdRoute
  '/(protected)/post/$postId': typeof protectedPostPostIdRoute
  '/(protected)/settings/groups': typeof protectedSettingsGroupsRoute
  '/(protected)/settings/organisations': typeof protectedSettingsOrganisationsRoute
  '/(protected)/settings/password-reset': typeof protectedSettingsPasswordResetRoute
  '/(protected)/settings/profile': typeof protectedSettingsProfileRoute
  '/(protected)/settings/profile-edit': typeof protectedSettingsProfileEditRoute
  '/(protected)/user/$userId': typeof protectedUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/registration'
    | '/verify-email'
    | '/settings'
    | '/news'
    | '/profile'
    | '/resources'
    | '/'
    | '/forum/$categoryId'
    | '/post/$postId'
    | '/settings/groups'
    | '/settings/organisations'
    | '/settings/password-reset'
    | '/settings/profile'
    | '/settings/profile-edit'
    | '/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/registration'
    | '/verify-email'
    | '/settings'
    | '/news'
    | '/profile'
    | '/resources'
    | '/'
    | '/forum/$categoryId'
    | '/post/$postId'
    | '/settings/groups'
    | '/settings/organisations'
    | '/settings/password-reset'
    | '/settings/profile'
    | '/settings/profile-edit'
    | '/user/$userId'
  id:
    | '__root__'
    | '/(protected)'
    | '/about'
    | '/login'
    | '/registration'
    | '/verify-email'
    | '/(protected)/settings'
    | '/(protected)/news'
    | '/(protected)/profile'
    | '/(protected)/resources'
    | '/(protected)/'
    | '/(protected)/forum/$categoryId'
    | '/(protected)/post/$postId'
    | '/(protected)/settings/groups'
    | '/(protected)/settings/organisations'
    | '/(protected)/settings/password-reset'
    | '/(protected)/settings/profile'
    | '/(protected)/settings/profile-edit'
    | '/(protected)/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegistrationRoute: typeof RegistrationRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/resources': {
      id: '/(protected)/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof protectedResourcesRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/profile': {
      id: '/(protected)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedProfileRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/news': {
      id: '/(protected)/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof protectedNewsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/user/$userId': {
      id: '/(protected)/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof protectedUserUserIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings/profile-edit': {
      id: '/(protected)/settings/profile-edit'
      path: '/profile-edit'
      fullPath: '/settings/profile-edit'
      preLoaderRoute: typeof protectedSettingsProfileEditRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/profile': {
      id: '/(protected)/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof protectedSettingsProfileRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/password-reset': {
      id: '/(protected)/settings/password-reset'
      path: '/password-reset'
      fullPath: '/settings/password-reset'
      preLoaderRoute: typeof protectedSettingsPasswordResetRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/organisations': {
      id: '/(protected)/settings/organisations'
      path: '/organisations'
      fullPath: '/settings/organisations'
      preLoaderRoute: typeof protectedSettingsOrganisationsRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/groups': {
      id: '/(protected)/settings/groups'
      path: '/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof protectedSettingsGroupsRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/post/$postId': {
      id: '/(protected)/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof protectedPostPostIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/forum/$categoryId': {
      id: '/(protected)/forum/$categoryId'
      path: '/forum/$categoryId'
      fullPath: '/forum/$categoryId'
      preLoaderRoute: typeof protectedForumCategoryIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedSettingsRouteRouteChildren {
  protectedSettingsGroupsRoute: typeof protectedSettingsGroupsRoute
  protectedSettingsOrganisationsRoute: typeof protectedSettingsOrganisationsRoute
  protectedSettingsPasswordResetRoute: typeof protectedSettingsPasswordResetRoute
  protectedSettingsProfileRoute: typeof protectedSettingsProfileRoute
  protectedSettingsProfileEditRoute: typeof protectedSettingsProfileEditRoute
}

const protectedSettingsRouteRouteChildren: protectedSettingsRouteRouteChildren =
  {
    protectedSettingsGroupsRoute: protectedSettingsGroupsRoute,
    protectedSettingsOrganisationsRoute: protectedSettingsOrganisationsRoute,
    protectedSettingsPasswordResetRoute: protectedSettingsPasswordResetRoute,
    protectedSettingsProfileRoute: protectedSettingsProfileRoute,
    protectedSettingsProfileEditRoute: protectedSettingsProfileEditRoute,
  }

const protectedSettingsRouteRouteWithChildren =
  protectedSettingsRouteRoute._addFileChildren(
    protectedSettingsRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedSettingsRouteRoute: typeof protectedSettingsRouteRouteWithChildren
  protectedNewsRoute: typeof protectedNewsRoute
  protectedProfileRoute: typeof protectedProfileRoute
  protectedResourcesRoute: typeof protectedResourcesRoute
  protectedIndexRoute: typeof protectedIndexRoute
  protectedForumCategoryIdRoute: typeof protectedForumCategoryIdRoute
  protectedPostPostIdRoute: typeof protectedPostPostIdRoute
  protectedUserUserIdRoute: typeof protectedUserUserIdRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedSettingsRouteRoute: protectedSettingsRouteRouteWithChildren,
  protectedNewsRoute: protectedNewsRoute,
  protectedProfileRoute: protectedProfileRoute,
  protectedResourcesRoute: protectedResourcesRoute,
  protectedIndexRoute: protectedIndexRoute,
  protectedForumCategoryIdRoute: protectedForumCategoryIdRoute,
  protectedPostPostIdRoute: protectedPostPostIdRoute,
  protectedUserUserIdRoute: protectedUserUserIdRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegistrationRoute: RegistrationRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
